"""Refactor to Rules-Based Availability

Revision ID: 65b73754294d
Revises: 2641aeb85ca2
Create Date: 2026-05-05 00:00:14.918310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65b73754294d'
down_revision: Union[str, Sequence[str], None] = '2641aeb85ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'day_of_week', name='uq_doctor_day_of_week')
    )
    op.drop_index(op.f('ix_available_slots_slot_date'), table_name='available_slots')
    op.drop_table('available_slots')
    op.add_column('appointments', sa.Column('appointment_date', sa.Date(), nullable=False))
    op.add_column('appointments', sa.Column('start_time', sa.Time(), nullable=False))
    op.add_column('appointments', sa.Column('end_time', sa.Time(), nullable=False))
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.drop_constraint(op.f('appointments_slot_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'slot_id')
    op.add_column('doctors', sa.Column('slot_duration_minutes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'slot_duration_minutes')
    op.add_column('appointments', sa.Column('slot_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('appointments_slot_id_fkey'), 'appointments', 'available_slots', ['slot_id'], ['id'])
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_column('appointments', 'end_time')
    op.drop_column('appointments', 'start_time')
    op.drop_column('appointments', 'appointment_date')
    op.create_table('available_slots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('slot_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('available_slots_doctor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('available_slots_pkey')),
    sa.UniqueConstraint('doctor_id', 'slot_date', 'start_time', name=op.f('uq_slot_doctor_date_time'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_available_slots_slot_date'), 'available_slots', ['slot_date'], unique=False)
    op.drop_table('doctor_schedules')
    # ### end Alembic commands ###
